### ISSUE TITLE
Sketch Keeps Crashing

### ISSUE THREAD

**Issue by Bas950** [sketch-hq/fig2sketch#101]
I downloaded this tool myself to see if I could get a better error than just a "Sketch has Crashed!"

```
ERROR:root:An unexpected error occurred when converting ROUNDED_RECTANGLE: YouTube ((1416, 2077)). It will be skipped
Traceback (most recent call last):
  File "converter/tree.py", line 74, in convert_node
  File "converter/tree.py", line 62, in convert_node
  File "converter/rectangle.py", line 12, in convert
  File "converter/base.py", line 105, in base_shape
  File "converter/base.py", line 82, in base_styled
  File "converter/base.py", line 141, in process_styles
  File "converter/style.py", line 75, in convert
  File "converter/style.py", line 75, in <listcomp>
  File "converter/style.py", line 107, in convert_fill
  File "converter/style.py", line 141, in convert_crop_image_to_mask
  File "converter/style.py", line 185, in cropped_image_layer
ZeroDivisionError: float division by zero
```

Using this tool it did make the sketch file, which I was able to import into Sketch, I am able to open the sketch file in the browser, but in the app I can't since it still makes the app crash.

**Comment by tmdvs** [comment]
This should now be resolved 🙏🏻 Please re-open if you still encounter this issue and if possible supply a sample document.
